language: python

python:
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"

install:
    - pip install poetry
    - poetry install

script:
    - poetry run nosetests --with-coverage --cover-package=har2tree tests/test.py
    - poetry run mypy .

after_success:
    - poetry run codecov
    - poetry run coveralls
